# The `service` block is the name of the service
service: hello

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  profile: orikamiserverless
  stage: ${opt:stage, 'staging'}
  deploymentBucket:
    name: com.serverless.deploy 
  environment:
    STAGE: ${opt:stage, 'staging'}

# The `functions` block defines what code to deploy
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          cors: true